const constants = {
  ERROR_BOUNDARY_HEADING_LABEL: 'Something went wrong.',
  NAVBAR_HOME_PAGE_TITLE: 'Home',
  NAVBAR_PRODUCT_PAGE_TITLE: 'Products',
  FOOTER_COPYRIGHT_CONTANT: '2023 Virtusa',
  FOOTER_NAVBAR_PRIVACY_PAGE_TITLE: 'Privacy',
  FOOTER_NAVBAR_TERMS_PAGE_TITLE: 'Terms',
  FOOTER_NAVBAR_SUPPORT_PAGE_TITLE: 'Support',
  SHIPPING_HEADING_LABEL: 'Shipping',
  MANAGE_CARD_HEADING_TITLE: 'Manage Cart Data',
  CART_BOX_TITLE: 'Your Cart',
  CART_TOTAL_TITLE: 'TOTAL (USD)',
  CART_NO_PRODUCTS_TITLE: 'No products in cart.',
  BILLING_DETAILS_HEADING_LABEL: 'Billing address',
  FIRST_NAME_LABEL: 'First Name',
  LAST_NAME_LABEL: 'Last Name',
  EMAIL_LABEL: 'Email',
  EMAIL_INFO_CONTENT: "We'll never share your email with anyone else.",
  ADDRESS_LABEL: 'Address',
  ADDRESS_2_LABEL: 'Address 2',
  OPTIONAL_LABEL: 'Optional',
  COUNTRY_LABEL: 'Country',
  STATE_LABEL: 'State',
  CITY_LABEL: 'City',
  PAYMENT_HEADING_LABEL: 'Payment',
  CASH_ON_DELIVERY_LABEL: 'Cash on delivery',
  ACCEPTS_COD_ONLY: 'Currently we only supports cash on delivery.',
  CHECKOUT_BUTTON_LABEL: 'Checkout',
  SHIPPING_AS_BILLING_CONTENT:
    'Shipping address is the same as my billing address',
  CANT_LONGER_ERROR_MESSAGE: "This value can't be longer than 32 characters.",
  CANT_LONGER_16_ERROR_MESSAGE: "This value can't be longer than 16 digits.",
  CANT_LESS_16_ERROR_MESSAGE: "This value can't be longer than 16 digits.",
  ONLY_ALPHABETS_ERROR_MESSAGE: 'Please enter alphabets only.',
  ONLY_DIGITS_ERROR_MESSAGE: 'Please enter digits(0-9) only.',
  VALID_EXPIRATION_DATE_ERROR_MESSAGE:
    'Not a valid expiration date. Example: MM/YY',
  REQUIRED_ERROR_MESSAGE: 'This field is required.',
  INVALIAD_EMAIL_ERROR_MESSAGE: 'Invalid email address.',
  THANK_YOU_PAGE_TITLE: 'Thank You !',
  THANK_YOU_PAGE_CONTENT: 'Your order has been placed successfully.',
  BACK_TO_HOME_BUTTON_TITLE: 'Back To Home',
  PRODUCT_NAME_TITLE: 'Product Name',
  PRODUCT_DESCRIPTION_TITLE: 'Brief Description',
  PRODUCT_PRICE_TITLE: 'Price',
  PRODUCT_QUANTITY_TITLE: 'Quantity',
  RELOAD_PRODUCTS_BUTTON_TITLE: 'reload default data',
  COMPLETE_PAYMENT_HEADING_TITLE: 'Review Summary and Complete Payment',
  COMPLETE_PAYMENT_ENTER_CODE_LABEL: 'Enter code',
  COMPLETE_PAYMENT_ENTER_CODE_NOTE_CONTENT:
    'Please enter below code to confirm your order.',
  COMPLETE_PAYMENT_CONFIRM_ORDER_LABEL: 'Confirm order',
  COMPLETE_PAYMENT_CARD_NAME_LABEL: 'Name on card',
  COMPLETE_PAYMENT_CARD_NAME_NOTE_CONTENT: 'Full name as displayed on card.',
  COMPLETE_PAYMENT_CARD_NO_LABEL: 'Credit card number',
  COMPLETE_PAYMENT_CARD_NO_NOTE_CONTENT: 'E.g.: 49..., 51..., 36..., 37...',
  COMPLETE_PAYMENT_CARD_EXPIRE_LABEL: 'Expiration',
  COMPLETE_PAYMENT_CARD_CVV_LABEL: 'CVV',
  COMPLETE_PAYMENT_SUBMIT_BUTTON_LABEL: 'Pay',
  COMPLETE_PAYMENT_NOT_AVIAL_CONTENT:
    'Unale to make payments please go back and try again.',
  ORDER_DETAILS_LABEL: 'Product Details',
  PAYMENT_DETAILS_LABEL: 'Payment Details',
  PAYMENT_DETAILS_TRANSACTION_LABEL: 'Transaction ID',
  PAYMENT_DETAILS_TOTAL_LABEL: 'Payment Total',
  PAYMENT_DETAILS_MODE_LABEL: 'Payment Mode',
  PAYMENT_DETAILS_STATUS_LABEL: 'Payment Status',
  PAYMENT_DETAILS_ISSUER_LABEL: 'Payment Issuer',
  PRODUCT_SUMMARY_LABEL: 'Product summary',
  CONFIRM_PAYMENT_LABEL: 'Complete payment',
  ADD_TO_CART_BUTTON_LABEL: 'Add to cart',
  QUANTITY_LABEL: 'Qunatity',
};
export default constants;
