const constants = {
  ERROR_BOUNDARY_HEADING_LABEL: 'Something went wrong.',
  NAVBAR_HOME_PAGE_TITLE: 'Home',
  NAVBAR_PRODUCT_PAGE_TITLE: 'Products',
  FOOTER_COPYRIGHT_CONTANT: '2023 Virtusa',
  FOOTER_NAVBAR_PRIVACY_PAGE_TITLE: 'Privacy',
  FOOTER_NAVBAR_TERMS_PAGE_TITLE: 'Terms',
  FOOTER_NAVBAR_SUPPORT_PAGE_TITLE: 'Support',
  SHIPPING_HEADING_LABEL: 'Shipping',
  MANAGE_CARD_HEADING_TITLE: 'Manage Cart Data',
  CART_BOX_TITLE: 'Your Cart',
  CART_TOTAL_TITLE: 'TOTAL (USD)',
  CART_NO_PRODUCTS_TITLE: 'No products in cart.',
  BILLING_DETAILS_HEADING_LABEL: 'Billing address',
  FIRST_NAME_LABEL: 'First Name',
  LAST_NAME_LABEL: 'Last Name',
  EMAIL_LABEL: 'Email',
  EMAIL_INFO_CONTENT: "We'll never share your email with anyone else.",
  ADDRESS_LABEL: 'Address',
  ADDRESS_2_LABEL: 'Address 2',
  OPTIONAL_LABEL: 'Optional',
  COUNTRY_LABEL: 'Country',
  STATE_LABEL: 'State',
  CITY_LABEL: 'City',
  PAYMENT_HEADING_LABEL: 'Payment',
  CASH_ON_DELIVERY_LABEL: 'Cash on delivery',
  ACCEPTS_COD_ONLY: 'Currently we only supports cash on delivery.',
  CHECKOUT_BUTTON_LABEL: 'Checkout',
  SHIPPING_AS_BILLING_CONTENT:
    'Shipping address is the same as my billing address',
  CANT_LONGER_ERROR_MESSAGE: "This value can't be longer than 32 characters.",
  ONLY_ALPHABETS_ERROR_MESSAGE: 'Please enter alphabets only.',
  REQUIRED_ERROR_MESSAGE: 'This field is required.',
  INVALIAD_EMAIL_ERROR_MESSAGE: 'Invalid email address.',
  THANK_YOU_PAGE_TITLE: 'Thank You !',
  THANK_YOU_PAGE_CONTENT: 'Your order has been placed successfully.',
  BACK_TO_HOME_BUTTON_TITLE: 'Back To Home',
  PRODUCT_NAME_TITLE: 'Product Name',
  PRODUCT_DESCRIPTION_TITLE: 'Brief Description',
  PRODUCT_PRICE_TITLE: 'Price',
  RELOAD_PRODUCTS_BUTTON_TITLE: 'reload default data'
};
export default constants;
